default = {
                "origin_x": 0,
                "origin_y": 4,
                "origin_z": 0,
                "width": 30,
                "height": 46,
                "depth": 2,
                "bouncer_offset": 4,
                "side_offset": 5,
                "top_offset": 2,
                "bottom_offset": 6,
                "peg_block": "sea_lantern",
                "hollow_area_block": "air",
                "front_wall_block": "barrier",
                "back_wall_block": "barrier",
                "background_block": "red_concrete",
                "cover_block": "smooth_quartz",
                "bottom_bar_block": "smooth_quartz",
                "right_bouncer_block": "repeating_command_block",
                "right_wall_block": "air",
                "right_cover_block": "oak_trapdoor",
                "left_bouncer_block": "repeating_command_block",
                "left_wall_block": "air",
                "left_cover_block": "oak_trapdoor",
        }